---
apiVersion: v1
kind: Namespace
metadata:
  name: devopsunify
  labels:
    app.kubernetes.io/managed-by: devopsunify
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: devopsunify
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    app.kubernetes.io/managed-by: devopsunify
