const axios = require('axios');
const yaml = require('yaml');
const fs = require('fs');
const path = require('path');
const logger = require('../utils/logger');

const JENKINS_URL   = () => process.env.JENKINS_URL;
const JENKINS_USER  = () => process.env.JENKINS_USER;
const JENKINS_TOKEN = () => process.env.JENKINS_API_TOKEN;

function auth() {
  return { username: JENKINS_USER(), password: JENKINS_TOKEN() };
}

class JenkinsService {
  // ── Crumb (CSRF token) ────────────────────────────────────────────────────
  async _getCrumb() {
    const res = await axios.get(`${JENKINS_URL()}/crumbIssuer/api/json`, { auth: auth() });
    return { [res.data.crumbRequestField]: res.data.crumb };
  }

  // ── Create or update a pipeline job ───────────────────────────────────────
  async createJob(jobName, jenkinsfileContent) {
    const configXml = this._buildJobConfigXml(jobName, jenkinsfileContent);
    const crumb = await this._getCrumb();
    const headers = { 'Content-Type': 'application/xml', ...crumb };

    try {
      // Try to create
      await axios.post(
        `${JENKINS_URL()}/createItem?name=${encodeURIComponent(jobName)}`,
        configXml,
        { auth: auth(), headers }
      );
      logger.info(`Jenkins job created: ${jobName}`);
    } catch (err) {
      if (err.response?.status === 400) {
        // Job exists — update it
        await axios.post(
          `${JENKINS_URL()}/job/${encodeURIComponent(jobName)}/config.xml`,
          configXml,
          { auth: auth(), headers }
        );
        logger.info(`Jenkins job updated: ${jobName}`);
      } else {
        throw err;
      }
    }
  }

  // ── Trigger a build ────────────────────────────────────────────────────────
  async triggerBuild(jobName, params = {}) {
    const crumb = await this._getCrumb();
    const hasParams = Object.keys(params).length > 0;
    const url = hasParams
      ? `${JENKINS_URL()}/job/${encodeURIComponent(jobName)}/buildWithParameters`
      : `${JENKINS_URL()}/job/${encodeURIComponent(jobName)}/build`;

    const res = await axios.post(url, null, {
      auth: auth(),
      headers: crumb,
      params: hasParams ? params : undefined,
    });

    // Jenkins returns Location header with queue item URL
    const queueUrl = res.headers['location'];
    return { queueUrl };
  }

  // ── Poll queue item → get build number ───────────────────────────────────
  async getBuildNumberFromQueue(queueUrl, maxWaitMs = 30000) {
    const deadline = Date.now() + maxWaitMs;
    while (Date.now() < deadline) {
      const res = await axios.get(`${queueUrl}api/json`, { auth: auth() });
      if (res.data.executable?.number) {
        return res.data.executable.number;
      }
      await new Promise(r => setTimeout(r, 2000));
    }
    throw new Error('Timed out waiting for Jenkins build number');
  }

  // ── Get build status ───────────────────────────────────────────────────────
  async getBuildStatus(jobName, buildNumber) {
    const res = await axios.get(
      `${JENKINS_URL()}/job/${encodeURIComponent(jobName)}/${buildNumber}/api/json`,
      { auth: auth() }
    );
    return {
      building: res.data.building,
      result: res.data.result,     // SUCCESS | FAILURE | ABORTED | null (still building)
      duration: res.data.duration,
      url: res.data.url,
    };
  }

  // ── Stream console log ─────────────────────────────────────────────────────
  async getConsoleLog(jobName, buildNumber, start = 0) {
    const res = await axios.get(
      `${JENKINS_URL()}/job/${encodeURIComponent(jobName)}/${buildNumber}/logText/progressiveText`,
      {
        auth: auth(),
        params: { start },
        responseType: 'text',
      }
    );
    return {
      text: res.data,
      moreData: res.headers['x-more-data'] === 'true',
      nextStart: parseInt(res.headers['x-text-size'] || '0'),
    };
  }

  // ── Set up GitHub webhook on job ───────────────────────────────────────────
  async configureGithubTrigger(jobName, secret) {
    // Handled in the job config XML — this method updates it
    logger.info(`GitHub trigger configured for ${jobName}`);
  }

  // ── Build job config XML ───────────────────────────────────────────────────
  _buildJobConfigXml(jobName, jenkinsfileContent) {
    const escaped = jenkinsfileContent
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

    return `<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job">
  <description>Auto-generated by DevOpsUnify for ${jobName}</description>
  <keepDependencies>false</keepDependencies>
  <properties>
    <org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
      <triggers>
        <com.cloudbees.jenkins.GitHubPushTrigger plugin="github">
          <spec></spec>
        </com.cloudbees.jenkins.GitHubPushTrigger>
      </triggers>
    </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
  </properties>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps">
    <script>${escaped}</script>
    <sandbox>true</sandbox>
  </definition>
  <triggers/>
  <disabled>false</disabled>
</flow-definition>`;
  }
}

module.exports = new JenkinsService();
